name: Release JS package @teamhanko/passkeys-next-auth-provider

on:
  workflow_run:
    workflows: ["Release JS package @teamhanko/passkeys-sdk"]
    branches: "main"
    types:
      - completed

defaults:
  run:
    working-directory: packages/js/passkeys-next-auth-provider

jobs:
  build-and-publish:
    needs: check-matching-versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: oven-sh/setup-bun@v1
      - run: bun i
      - run: bun run build
      - name: publish passkeys-next-auth-provider
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISHING_SECRET }}
